{ config, pkgs, lib, ... }:
let
  cosmicDir = "${config.xdg.configHome}/cosmic";

  # The USER half of the desktop environment. modules/nixos/cosmic.nix is the
  # system half; a host imports both, and nothing else in modules/home names
  # COSMIC. Swapping DE = write the same pair for the new one and flip two import
  # lines per host. Two things live here:
  #
  #   1. mime defaults that point at COSMIC's own apps (bottom of the file)
  #   2. gtk-theme-sync — makes old GTK apps follow COSMIC's light/dark switch
  #
  # ── 2. gtk-theme-sync ────────────────────────────────────────────
  #
  # Why this is needed at all — three tiers of GTK app, only two of which work
  # on their own:
  #
  #   libadwaita (GTK4)  read `color-scheme` from the org.freedesktop.appearance
  #                      portal. xdg-desktop-portal-cosmic answers it, so these
  #                      already follow COSMIC live. Nothing to do.
  #   COSMIC/iced apps   read com.system76.CosmicTheme.* directly. Also fine.
  #   plain GTK3         read GtkSettings, i.e. ~/.config/gtk-3.0/settings.ini.
  #                      GTK only consults the portal for those keys when it
  #                      thinks it is sandboxed (gdk_should_use_portal()), which
  #                      a native Nix build is not — so nothing ever tells them
  #                      the desktop went dark. THIS is the gap: GIMP, Meld,
  #                      Transmission, nm-connection-editor, and every other
  #                      pre-libadwaita GTK3 app stays light on a dark desktop.
  #
  # So: watch COSMIC's is_dark flag and rewrite settings.ini. The theme itself is
  # adw-gtk3 (installed system-wide in modules/nixos/cosmic.nix) because it is the
  # only maintained GTK3 theme that tracks current Adwaita, so a GTK3 app sitting
  # next to a GTK4 one does not look like a different decade.
  #
  # Deliberately NOT trying to reproduce COSMIC's accent in GTK: adw-gtk3 has no
  # accent hook, and generating a whole GTK stylesheet from COSMIC's RON theme is
  # exactly the fragile-across-epochs machinery this replaced.
  sync = pkgs.writeShellApplication {
    name = "gtk-theme-sync";
    runtimeInputs = [ pkgs.coreutils pkgs.glib ];
    text = ''
      cosmic_dir="${cosmicDir}"

      # Default to dark on anything unexpected — a missing file (COSMIC not yet
      # run), an unreadable one, or a value we do not recognise. is_dark is a
      # plain boolean and is the one COSMIC config key that will not change shape.
      is_dark=true
      mode_file="$cosmic_dir/com.system76.CosmicTheme.Mode/v1/is_dark"
      if [ -r "$mode_file" ]; then
        case "$(cat "$mode_file")" in
          *false*) is_dark=false ;;
          *true*)  is_dark=true  ;;
        esac
      fi

      if [ "$is_dark" = true ]; then
        gtk3_theme="adw-gtk3-dark"; prefer_dark=true;  scheme="prefer-dark"
      else
        gtk3_theme="adw-gtk3";      prefer_dark=false; scheme="prefer-light"
      fi

      # write_ini <dir> <body...> — rename rather than write in place so a GTK app
      # reading the file mid-update can never see half of it. GTK watches these
      # paths with a GFileMonitor, so most apps restyle live; the stubborn ones
      # pick it up on next launch.
      write_ini() {
        dir="$1"; shift
        mkdir -p "$dir"
        {
          echo "# Generated by gtk-theme-sync. Do not edit — rewritten on every"
          echo "# COSMIC light/dark change. Source: modules/home/cosmic.nix"
          echo "[Settings]"
          printf '%s\n' "$@"
        } > "$dir/settings.ini.new"
        mv -f "$dir/settings.ini.new" "$dir/settings.ini"
      }

      # GTK3 needs both keys: the theme name picks the stylesheet, and
      # prefer-dark is what apps that ask GtkSettings "am I dark?" actually read
      # to choose their own icon/text colours.
      write_ini "${config.xdg.configHome}/gtk-3.0" \
        "gtk-theme-name=$gtk3_theme" \
        "gtk-application-prefer-dark-theme=$prefer_dark"

      # GTK4 gets prefer-dark ONLY. adw-gtk3 is a GTK3 stylesheet and naming it
      # here would leave GTK4 apps unstyled; the built-in theme has a dark variant
      # and this is the switch for it. libadwaita apps ignore this and use the
      # portal, which is correct — they are already following COSMIC.
      write_ini "${config.xdg.configHome}/gtk-4.0" \
        "gtk-application-prefer-dark-theme=$prefer_dark"

      # Belt and braces for the apps that read GSettings instead of settings.ini
      # (anything using GNOME's desktop schemas, plus Flatpaks via the portal's
      # GSettings backend). COSMIC already sets color-scheme itself; gtk-theme it
      # does not, and that is the one adw-gtk3 needs. Non-fatal: the schemas are
      # only present because the COSMIC module pulls them in, and a session
      # without a running dbus (e.g. running this by hand over SSH) should still
      # get the settings.ini half of the job done.
      if ! gsettings set org.gnome.desktop.interface gtk-theme "$gtk3_theme" 2>/dev/null; then
        echo "gtk-theme-sync: gsettings unavailable — settings.ini written anyway" >&2
      else
        gsettings set org.gnome.desktop.interface color-scheme "$scheme"
      fi

      echo "gtk-theme-sync: $gtk3_theme"
    '';
  };
in
{
  # Also on PATH, so you can run `gtk-theme-sync` by hand to see what it decided —
  # the one-line summary it prints is the whole diagnostic.
  home.packages = [ sync ];

  systemd.user.services.gtk-theme-sync = {
    Unit = {
      Description = "Apply the COSMIC light/dark mode to GTK apps";
      PartOf = [ "graphical-session.target" ];
    };
    Service = {
      Type = "oneshot";
      ExecStart = lib.getExe sync;
    };
    # Runs once at session start as well as on every change, so settings.ini is
    # correct before the first GTK app opens rather than one toggle later.
    Install.WantedBy = [ "graphical-session.target" ];
  };

  systemd.user.paths.gtk-theme-sync = {
    Unit.Description = "Watch COSMIC's light/dark mode";
    Path = {
      # Watching the config file rather than listening for the portal's D-Bus
      # SettingChanged signal: a .path unit is declarative and needs no
      # long-running listener parsing D-Bus output.
      #
      # Both Changed and Modified because COSMIC's config writer renames a temp
      # file over is_dark (an IN_MOVED_TO, which is PathChanged) but a plain
      # in-place write (PathModified) is equally legal — catching only one of the
      # two would make the sync work until the day it silently did not.
      PathChanged  = [ "${cosmicDir}/com.system76.CosmicTheme.Mode/v1/is_dark" ];
      PathModified = [ "${cosmicDir}/com.system76.CosmicTheme.Mode/v1/is_dark" ];
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  # ── 1. mime defaults for COSMIC's own apps ───────────────────────
  # The DE-agnostic handlers (mpv, qimgv, firefox) are in modules/home/xdg.nix;
  # these are the ones that would change with the desktop, so they live with it.
  # defaultApplications merges across modules, so the two lists become one.
  xdg.mimeApps.defaultApplications = {
    # Directories: what opens when an app says "show in file manager". cosmic-files
    # ships the only inode/directory handler, but nothing sets it as the *default*.
    "inode/directory" = "com.system76.CosmicFiles.desktop";

    # Which terminal "Open in Terminal" uses. cosmic-files falls back to
    # CosmicTerm when unset, so this is for everything ELSE that resolves a
    # terminal through xdg-mime rather than hardcoding COSMIC's — most things.
    "x-scheme-handler/terminal" = "com.system76.CosmicTerm.desktop";

    # Plain text. cosmic-edit is kept installed precisely so this has somewhere to
    # go (see modules/nixos/cosmic.nix).
    "text/plain" = "com.system76.CosmicEdit.desktop";

    # cosmic-reader is the only PDF viewer installed (papers was dropped from
    # modules/nixos/apps.nix rather than keeping two); it also ships a
    # thumbnailer, so PDFs get previews in cosmic-files.
    "application/pdf" = "com.system76.CosmicReader.desktop";
  };
}
