{ config, pkgs, lib, repoDir, ... }:
let
  cosmicDir = "${config.xdg.configHome}/cosmic";
  alacDir   = "${config.xdg.configHome}/alacritty";

  # Follows COSMIC's appearance in the terminal. Two separate jobs, deliberately
  # ordered so the fragile one cannot break the robust one:
  #
  #   1. light/dark — pick one of two palettes committed in this repo. Driven by
  #      COSMIC's is_dark flag, which is a plain boolean and will not change shape.
  #   2. accent — recolour ONLY the cursor and the selection. Read out of COSMIC's
  #      internal RON theme, which is the part that can change between epochs; if
  #      the parse yields nothing the palette's own cursor colour just stays.
  #
  # The accent deliberately does NOT touch the 16 ANSI colours. Those carry
  # meaning rather than decoration — red is "error", green is "added line", and
  # every tool from git to ls depends on that. Pouring a purple accent into one
  # of them would make `git diff` render deletions in purple. Cursor and selection
  # are the only slots with no semantics attached, so they are where it belongs.
  sync = pkgs.writeShellApplication {
    name = "cosmic-theme-sync";
    runtimeInputs = [ pkgs.gawk pkgs.coreutils ];
    text = ''
      cosmic_dir="${cosmicDir}"
      alac_dir="${alacDir}"
      out="$alac_dir/colors-active.toml"

      # ── 1. light or dark ──────────────────────────────────────────
      # Default to dark on anything unexpected: a missing file (COSMIC not yet
      # run), an unreadable one, or a value we do not recognise. Dark matches the
      # committed fallback, so the worst case is "nothing appears to happen".
      is_dark=true
      mode_file="$cosmic_dir/com.system76.CosmicTheme.Mode/v1/is_dark"
      if [ -r "$mode_file" ]; then
        case "$(cat "$mode_file")" in
          *false*) is_dark=false ;;
          *true*)  is_dark=true  ;;
        esac
      fi

      if [ "$is_dark" = true ]; then
        palette="${repoDir}/config/alacritty/colors-dark.toml"
        theme_id="com.system76.CosmicTheme.Dark"
      else
        palette="${repoDir}/config/alacritty/colors-light.toml"
        theme_id="com.system76.CosmicTheme.Light"
      fi

      # The palettes live in the working tree (like every other editable config
      # here), so a missing repo must not leave a half-written file behind.
      if [ ! -r "$palette" ]; then
        echo "cosmic-theme-sync: no palette at $palette — leaving colours alone" >&2
        exit 0
      fi

      # ── 2. accent → hex, best effort ──────────────────────────────
      # COSMIC stores each config key as its own file, the accent being a RON
      # Component whose `base` is the colour we want. Two things are deliberately
      # loose here: serde may render an Srgba either positionally as
      # `(0.2, 0.5, 0.9, 1.0)` or by field as `(red: 0.2, green: ...)`, so we take
      # the first three numbers after `base:` whichever way it was written; and
      # any failure at all yields an empty accent, which simply skips step 3.
      accent=""
      accent_file="$cosmic_dir/$theme_id/v1/accent"
      if [ -r "$accent_file" ]; then
        accent=$(awk '
          # everything from the first "base:" onward, then the first 3 floats
          index($0, "base:") { collecting = 1 }
          collecting {
            line = line " " $0
            n = split(line, tok, /[^0-9.]+/)
            c = 0
            for (i = 1; i <= n; i++) if (tok[i] ~ /^[0-9]*\.?[0-9]+$/) { c++; v[c] = tok[i] + 0 }
            if (c >= 3) {
              printf "#%02x%02x%02x\n", \
                int(v[1] * 255 + 0.5), int(v[2] * 255 + 0.5), int(v[3] * 255 + 0.5)
              exit
            }
          }
        ' "$accent_file" 2>/dev/null) || accent=""
      fi

      # ── 3. write the file alacritty imports last ──────────────────
      mkdir -p "$alac_dir"
      {
        echo "# Generated by cosmic-theme-sync. Do not edit — rewritten on every"
        echo "# COSMIC appearance change. Source: modules/home/cosmic-theme-sync.nix"
        echo
        if [ -n "$accent" ]; then
          # Strip the palette's OWN cursor/selection tables before appending ours.
          # TOML forbids declaring the same table twice, so emitting a second
          # [colors.cursor] would make the whole file unparseable and alacritty
          # would reject the import outright — losing the palette too, not just
          # the accent. Drop each table from its header to the next one.
          awk '
            /^\[colors\.(cursor|selection)\]/ { skip = 1; next }
            /^\[/                              { skip = 0 }
            !skip
          ' "$palette"
          echo "# ── COSMIC accent ($accent) ──"
          echo "[colors.cursor]"
          echo "text   = \"CellBackground\""
          echo "cursor = \"$accent\""
          echo
          echo "[colors.selection]"
          echo "background = \"$accent\""
          echo "text       = \"CellForeground\""
        else
          cat "$palette"
        fi
      } > "$out.new"

      # Rename rather than write in place: it is atomic, so alacritty can never
      # read a half-written palette, and its watcher treats a rename-to as a
      # change (only rename-FROM is ignored, as that means deletion).
      mv -f "$out.new" "$out"

      echo "cosmic-theme-sync: $([ "$is_dark" = true ] && echo dark || echo light)''${accent:+, accent $accent}"
    '';
  };
in
{
  # Also on PATH, so you can run `cosmic-theme-sync` by hand to see what it
  # decided — the one-line summary it prints is the whole diagnostic.
  home.packages = [ sync ];

  systemd.user.services.cosmic-theme-sync = {
    Unit = {
      Description = "Apply the COSMIC appearance to the alacritty palette";
      PartOf = [ "graphical-session.target" ];
    };
    Service = {
      Type = "oneshot";
      ExecStart = lib.getExe sync;
    };
    # Runs once at session start as well as on every change. That start-up run is
    # what makes colors-active.toml exist BEFORE you open a terminal, which
    # matters: alacritty only reloads for paths it already knew about when it
    # started, so a terminal opened before the file first appeared has to be
    # restarted once to pick it up. After that, changes apply live.
    Install.WantedBy = [ "graphical-session.target" ];
  };

  systemd.user.paths.cosmic-theme-sync = {
    Unit.Description = "Watch COSMIC's appearance settings";
    Path = {
      # Watching COSMIC's config files rather than listening for the portal's
      # D-Bus SettingChanged signal: a .path unit is declarative and needs no
      # long-running listener parsing D-Bus output. The accent files are watched
      # too because changing the accent does not touch is_dark.
      PathChanged = [
        "${cosmicDir}/com.system76.CosmicTheme.Mode/v1/is_dark"
        "${cosmicDir}/com.system76.CosmicTheme.Dark/v1/accent"
        "${cosmicDir}/com.system76.CosmicTheme.Light/v1/accent"
      ];
      PathModified = [
        "${cosmicDir}/com.system76.CosmicTheme.Mode/v1/is_dark"
      ];
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };
}
